# Generated by Django 3.1.4 on 2021-01-01 12:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default=core.models.word_default, max_length=25),
        ),
    ]
