# Generated by Django 3.1.4 on 2021-01-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_word_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='letters',
            field=models.CharField(default='', max_length=27),
        ),
    ]
