# Generated by Django 3.1.4 on 2021-01-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210102_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='letters',
            field=models.CharField(default=None, max_length=27, null=True),
        ),
    ]
