# Generated by Django 3.1.4 on 2021-01-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210102_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='letters',
        ),
    ]
