# Generated by Django 3.1.4 on 2021-01-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_word_letters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='letters',
        ),
    ]
